package revature.data.utils.exceptions;

public class DataSourceExceptions extends RuntimeException{
    public DataSourceExceptions(String message, Throwable cause){
        super(message,cause);
    }
}
